language: ruby
bundler_args: --without development production
rvm:
  - 2.0.0
  - 2.1.1
  - 1.9.3
before_install:
  - travis_retry gem install bundler  
before_script:
  - mysql -e 'create database huginn_test;'
  - bundle exec rake db:migrate db:test:prepare
script: "bundle exec rake"
notifications:
  irc:
    channels:
      - "chat.freenode.net#huginn"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
