sudo: false
language: ruby
env:
  global:
    - APP_SECRET_TOKEN=b2724973fd81c2f4ac0f92ac48eb3f0152c4a11824c122bcf783419a4c51d8b9bba81c8ba6a66c7de599677c7f486242cf819775c433908e77c739c5c8ae118d
  matrix:
    - DATABASE_ADAPTER=mysql2
    - DATABASE_ADAPTER=postgresql DATABASE_USERNAME=postgres
rvm:
- 2.0.0
- 2.1.5
- 2.2.0
cache: bundler
bundler_args: --without development production
before_script:
- bundle exec rake db:create db:migrate
script: bundle exec rake
notifications:
  irc:
    channels:
    - chat.freenode.net#huginn
    template:
    - "<%{author}> %{branch} - %{commit} (%{commit_message}): %{message}"
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5f92cc0393c6f1defe0d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
