development:
  address: <%= ENV['SMTP_SERVER'] || "smtp.gmail.com" %>
  port: <%= ENV['SMTP_PORT'] || 587 %>
  domain: <%= ENV['SMTP_DOMAIN'] %>
  authentication: <%= ENV['SMTP_AUTHENTICATION'] || "plain" %>
  enable_starttls_auto: <%= ENV['SMTP_ENABLE_STARTTLS_AUTO'] == 'true' ? true : false %>
  user_name: <%= ENV['SMTP_USER_NAME'] || "" %>
  password: <%= ENV['SMTP_PASSWORD'] || "" %>
  openssl_verify_mode: <%= ENV['SMTP_OPENSSL_VERIFY_MODE'].presence || 'null' %>
  ca_path: <%= ENV['SMTP_OPENSSL_CA_PATH'].presence || 'null' %>
  ca_file: <%= ENV['SMTP_OPENSSL_CA_FILE'].presence || 'null' %>

staging:
  address: <%= ENV['SMTP_SERVER'] || "smtp.gmail.com" %>
  port: <%= ENV['SMTP_PORT'] || 587 %>
  domain: <%= ENV['SMTP_DOMAIN'] %>
  authentication: <%= ENV['SMTP_AUTHENTICATION'] || "plain" %>
  enable_starttls_auto: <%= ENV['SMTP_ENABLE_STARTTLS_AUTO'] == 'true' ? true : false %>
  user_name: <%= ENV['SMTP_USER_NAME'] || "" %>
  password: <%= ENV['SMTP_PASSWORD'] || "" %>
  openssl_verify_mode: <%= ENV['SMTP_OPENSSL_VERIFY_MODE'].presence || 'null' %>
  ca_path: <%= ENV['SMTP_OPENSSL_CA_PATH'].presence || 'null' %>
  ca_file: <%= ENV['SMTP_OPENSSL_CA_FILE'].presence || 'null' %>

production:
  address: <%= ENV['SMTP_SERVER'] || "smtp.gmail.com" %>
  port: <%= ENV['SMTP_PORT'] || 587 %>
  domain: <%= ENV['SMTP_DOMAIN'] %>
  authentication: <%= ENV['SMTP_AUTHENTICATION'] || "plain" %>
  enable_starttls_auto: <%= ENV['SMTP_ENABLE_STARTTLS_AUTO'] == 'true' ? true : false %>
  user_name: <%= ENV['SMTP_USER_NAME'] || "" %>
  password: <%= ENV['SMTP_PASSWORD'] || "" %>
  openssl_verify_mode: <%= ENV['SMTP_OPENSSL_VERIFY_MODE'].presence || 'null' %>
  ca_path: <%= ENV['SMTP_OPENSSL_CA_PATH'].presence || 'null' %>
  ca_file: <%= ENV['SMTP_OPENSSL_CA_FILE'].presence || 'null' %>
